### ISSUE TITLE
[Game] Sports Illustrated for Kids - Football has broken sound

### ISSUE THREAD

**Issue by Dartz150** [Gericom/GBARunner3#106]
### Game Info
**Game Title:** Sports Illustrated for Kids - Football
**TID:** AKFE
**REG:** USA
### GBARunner3 info
**Commit:** 14b27ce
**Build Date:** 13 Nov 2023
**Branch:** develop
**Patches on repo:**  
**Console:** DSi
**Device:** SD
**wram icache:** off
**Flashcard Model:** 

 ### **Compatibility:** Sound Issues

**Notes:** Sound is broken: from the start and during the whole game, only a screeching sound is heard (similar to a "ejected GBA cart" corrupted sound), the same happens in DS mode. Note that this is not a regression, this has been happening since sound has been implemented. ARM7 mem prio gives the same result.

**Comment by Gericom** [comment]
Does the game stream audio from the rom?

**Comment by Gericom** [comment]
> Does the game stream audio from the rom?

It does not

It is actually caused by the wrong values returned from bios reads #50
