### ISSUE TITLE
GBA border

### ISSUE THREAD

**Issue by chronoss09** [Gericom/GBARunner3#128]
Hi !!!

I test this feature with a gbaborders folder on my sd card but it don't work, there is a option for that ?

**Comment by Dartz150** [comment]
> Hi !!!
> 
> I test this feature with a gbaborders folder on my sd card but it don't work, there is a option for that ?

GBARunner3 is a complete re-write so many features available in GBARunner2 are not implemented yet, this feature being one example. 

You could change your title and turn this topic into a feature request for GBA border support though, it may be added eventually.

**Comment by ahmadyogi543** [comment]
Hello, just asking this since I can't find any tutorial regarding how to setup the border and also if I could customize the border. Thanks in advance (pun intended)
