### ISSUE TITLE
[Game] Contra Advance - The Alien Wars EX - Wrong SFX sound being played at random

### ISSUE THREAD

**Issue by Dartz150** [Gericom/GBARunner3#138]
### Game Info
**Game Title:** Contra Advance - The Alien Wars EX
**TID:** AAWE
**REG:** USA
**SAVETYPE:** NO_SAVE
**Hicode:** 
**Bitmap:** ✔
### Hardware
**Console:** DSi
**Media:** SD
**Flashcard:** 
### GBARunner3 info
**Commit:** 9b7caeb
**Build Date:** 28 Dec 2023
**Branch:** develop
**JIT Patches on repo:**  
### Configuration
**Base Shift:** 
**JIT Patches:** 
**SMoC Patches:** 
**wram icache:** 

 ### **Compatibility:** Sound Issues

**Notes:** Wrong sound effects used for the first enemy you meet that throws a grenade and for the shield power up sfx, weapon power up, and for bombs of the wall enemy in the linked picture and the same for exploding buildings and granade explosions. Sometimes this doesn't happen on the first stage. and starts happening after getting to the 2nd stage boss. https://cdn.discordapp.com/attachments/620310871800807466/1155629543839760484/20230925_001632.jpg

Interestingly enough, No$GBA has the same issue, and throws the following exceptions when the wrong SFX sounds are triggered:

![image](https://github.com/Gericom/GBARunner3/assets/42103728/163e1203-8582-42b1-9095-b647794b5c9c)

![image](https://github.com/Gericom/GBARunner3/assets/42103728/6d3ffc0b-6827-43fd-b969-22d714f0337a)

**Comment by Gericom** [comment]
Seems like rom open bus.
