### ISSUE TITLE
[feature request] allow settings to be set on a per game basis

### ISSUE THREAD

**Issue by therealteamplayer** [Gericom/GBARunner3#143]
creating a request for this as I don't think this was in gbarunner2. it would be very useful to save settings per-game to fix issues that may only occur with specific games.

could also have a database of default settings for games that need them, like how dolphin handles games that need certain hacks turned off

**Comment by Dartz150** [comment]
> creating a request for this as I don't think this was in gbarunner2. it would be very useful to save settings per-game to fix issues that may only occur with specific games.
> 
> could also have a database of default settings for games that need them, like how dolphin handles games that need certain hacks turned off

This feature is already implemented, you can modify per-game settings contained in this folder, and you can also add new ones for any game https://github.com/Gericom/GBARunner3/tree/develop/configs

Besides manual JIT patches used to fix compatibility issues, per-game config files can also be used to override general settings. So far, these settings are available, an explanation for each will be added to a readme file in the future:

```{
    "runSettings": {
        "enableWramICache": true,
        "enableEwramDCache": true
        "selfModifyingPatchAddresses": [
        ],
        "lJitPatchesAddresses": [
        ],
    },
    "displaySettings": {
        "gbaScreen": "top",
        "gbaColorCorrection": "Agb001",
        "gbaScreenBrightness": 16,
        "enableCenterAndMask": true,
        "centerOffsetX": 8,
        "centerOffsetY": 16,
        "maskWidth": 240,
        "maskHeight": 160
    },
    "gameSettings": {
        "saveType": "none"
    }
}
