### ISSUE TITLE
[feature request] exit gbarunner

### ISSUE THREAD

**Issue by rofl0r** [Gericom/GBARunner3#144]
i can't seem to find a way to quit gbarunner, once it's launched. it'd be great to get back to the menu other than rebooting the device, which takes a lot of time to reload everything.

> Describe the solution you'd like

add option "exit gbarunner" to gbarunner menu, which returns to twilightmenu or whatever app it's been launched from.

**Comment by Gericom** [comment]
Duplicate of #10.
