### ISSUE TITLE
Regression: Some games are freezing in specific spots since 2f0609f

### ISSUE THREAD

**Issue by Dartz150** [Gericom/GBARunner3#154]
### Game Info
**Game Title:** Yu-Gi-Oh! - 7 Trials to Glory - World Championship Tournament 2005, Secret Agent Barbie - Royal Jewels Mission
**TID:** BY7E
**REG:** USA
**SAVETYPE:** SRAM_256K
**Hicode:** 
**Bitmap:** 
### Hardware
**Console:** DSi
**Media:** SD
**Flashcard:** 
### GBARunner3 info
**Commit:** d1efd9b
**Build Date:** 7 Apr 2024
**Branch:** develop
**MJP on Repo:** no
**Base Shift:** 
**M-JIT Patches:** ✔
**SMoC Patches:** 
**wram icache:** 

 ### **Compatibility:** Unplayable

**Notes:** Both games have a regression as of commit 2f0609f, both freezing the console in a black screen after in the title screen. More titles will be added if found.
**Tester:** Dartz

**Comment by Dartz150** [comment]
Same issue found in `Yu-Gi-Oh! GX - Duel Academy`

**Comment by Gericom** [comment]
Barbie was fixed in 08eb85171fd55d8451db80ef4b6ed24ca3a7310d and unrelated to 2f0609f

**Comment by Dartz150** [comment]
As of commit [1bd147d](https://github.com/Gericom/GBARunner3/commit/1bd147ddfeaab423e62a6f8aad32d885617452a8), issues related to crashes with the irq yielding feature no longer occur, and all the mentioned games are now fixed.
