### ISSUE TITLE
[request] Simple graphic filters

### ISSUE THREAD

**Issue by KaroNiko** [Gericom/GBARunner3#166]
Would it be possible to eventually implement some graphic shaders/filters? I'm referring to the simplest ones, which wouldn't impact the emulator's performance (linear, 2xSai, Super Eagle, Advanced Mame etc.) I know it's not a priority now, but will it be possible in the future? Some titles, especially on DSi XL, are too coarse and edgy.
Thank you for your continued and priceless commitment. Good work!

**Comment by thanone2** [comment]
I like this idea

**Comment by Gericom** [comment]
I doubt this would be possible with the limited processing power the DS has

**Comment by thanone2** [comment]
It can upscale and add filters to gameboy color games well. I'm sure it could do ok-ish but the dsi would do much better than the og ds

**Comment by KaroNiko** [comment]
Sure. I was mainly referring to the DSi. As already noted, "Lameboy" (and then"Gameyob") already used a filter many years ago, with excellent graphic results and without impacting the emulation speed in the slightest, even on DS phat/lite. Thanks anyway for the replies.

**Comment by Dartz150** [comment]
There's no point into adding scaling filters to a 1:1 unscaled display...

**Comment by KaroNiko** [comment]
Okay. Thanks chief for the clarification. And scale the image until it fills the screen, eliminating the black frame, and then applying bilinear filtering; I assume the performance would get worse, but would it be technically possible? Maybe as an optional possibility, via a specific menu option? Whoever responds, don't get angry or jump at my throat; I just want to know if it would be theoretically possible, since it's not technically a gba emulation.

**Comment by Gericom** [comment]
This is just not going to happen. The amount of upscale is already very small, and there's definitely no cpu time left to perform any pixel processing.
