### ISSUE TITLE
All games boot to black screen

### ISSUE THREAD

**Issue by namenamenam** [Gericom/GBARunner3#167]
Regardless of the game selected:

1. GBARunner3 starts
2. Splash screen is displayed correctly
3. Screen flashes purple for about 1 second (the same shade of purple as the splash), covering the whole screen (this only happens sometimes?)
4. Screen goes black, no game starts

I have tested Sonic Advance, Super Mario Advance 4, and Donkey Kong Country.

Technical info:
System: DSi on 1.4.5U
Booted through TWiLight Menu++ 27.10.0
SD: SanDisk microSD 32GB MBR with 32KB clusters

No games have been manually patched by me, but all games have JSON files present for JIT patching by GBR3.
Also notable that there does not seem to be a way to configure GBR3, neither through itself or TWL++.

**Comment by Gericom** [comment]
Make sure you have the gba bios in _gba/bios.bin

**Comment by namenamenam** [comment]
Yes, the bios.bin file exists in /_gba/, it is 16 KB

**Comment by namenamenam** [comment]
Turned out the BIOS was corrupt. Re-dumped the BIOS and all is OK now.
