### ISSUE TITLE
Final Fantasy VI Advance - Missing "Healt & Safety" screen when the game boots.

### ISSUE THREAD

**Issue by Dartz150** [Gericom/GBARunner3#20]
This also happened in GBArunner2, there's only a warning yellow sign showing up at the right corner and the rest of the screen is white, when characters should appears instead.

**Comment by Dartz150** [comment]
OAM view of this screen in no$GBA

![image](https://github.com/Gericom/GBARunner3/assets/42103728/7dfe5e0b-6701-4072-9df4-212173d5ea54)

The missing text is in BG2. For some reason, trying to check Tiles 2 tab crashes no$GBA:
![image](https://github.com/Gericom/GBARunner3/assets/42103728/6136f24e-1a41-4a16-a59d-a007a469e689)

**Comment by Gericom** [comment]
It's bitmap appearently

**Comment by Dartz150** [comment]
> It's bitmap appearently

I've tested this on GBARunner2 that has bitmap support and it shows the same issue.

**Comment by zenseii** [comment]
> > It's bitmap appearently
> 
> I've tested this on GBARunner2 that has bitmap support and it shows the same issue.

Did you check it with the bitmap branch of gbarunner3?

**Comment by Dartz150** [comment]
This also happens in the bitmap branch, dunno if this could affect other areas of the game or games.

**Comment by zenseii** [comment]
This has been reported as fixed so maybe we should close it, @Dartz150 ?

**Comment by Dartz150** [comment]
This has been fixed on the latest bitmap branch, closed.
