### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by godreborn** [Gericom/GBARunner3#21]
this is what happens when I try to compile.  I'm using ubuntu 20.04 btw.

linking test.elf
ArmDtcm.o: in function `memu_armDispatchTable':
(.dtcm+0x8): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armLdmStmRnTable_0' defined in .dtcm section in ArmLdmStmRn.o
(.dtcm+0xa): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armStmRdTable' defined in .dtcm section in ArmLdmStmRd.o
(.dtcm+0x10): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armLdmStmRnTable_0' defined in .dtcm section in ArmLdmStmRn.o
(.dtcm+0x12): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armLdmRdTable' defined in .dtcm section in ArmLdmStmRd.o
(.dtcm+0x18): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armLdmStmRnTable_1' defined in .dtcm section in ArmLdmStmRn.o
(.dtcm+0x1a): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armStmRdTable' defined in .dtcm section in ArmLdmStmRd.o
(.dtcm+0x20): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armLdmStmRnTable_1' defined in .dtcm section in ArmLdmStmRn.o
(.dtcm+0x22): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armLdmRdTable' defined in .dtcm section in ArmLdmStmRd.o
(.dtcm+0x28): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armLdmStmRnTable_0' defined in .dtcm section in ArmLdmStmRn.o
(.dtcm+0x2a): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armStmRdTable' defined in .dtcm section in ArmLdmStmRd.o
(.dtcm+0x30): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status
make[3]: *** [/home/godreborn/GBARunner3/code/test/arm9/Makefile:146: /home/godreborn/GBARunner3/code/test/arm9/test.elf] Error 1
make[2]: *** [Makefile:130: build] Error 2
make[2]: Leaving directory '/home/godreborn/GBARunner3/code/test/arm9'
make[1]: *** [Makefile:49: arm9/test.elf] Error 2
make[1]: *** Waiting for unfinished jobs....
linking test.elf
ArmDtcm.o: in function `memu_armDispatchTable':
(.dtcm+0x8): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armLdmStmRnTable_0' defined in .dtcm section in ArmLdmStmRn.o
(.dtcm+0xa): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armStmRdTable' defined in .dtcm section in ArmLdmStmRd.o
(.dtcm+0x10): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armLdmStmRnTable_0' defined in .dtcm section in ArmLdmStmRn.o
(.dtcm+0x12): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armLdmRdTable' defined in .dtcm section in ArmLdmStmRd.o
(.dtcm+0x18): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armLdmStmRnTable_1' defined in .dtcm section in ArmLdmStmRn.o
(.dtcm+0x1a): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armStmRdTable' defined in .dtcm section in ArmLdmStmRd.o
(.dtcm+0x20): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armLdmStmRnTable_1' defined in .dtcm section in ArmLdmStmRn.o
(.dtcm+0x22): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armLdmRdTable' defined in .dtcm section in ArmLdmStmRd.o
(.dtcm+0x28): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armLdmStmRnTable_0' defined in .dtcm section in ArmLdmStmRn.o
(.dtcm+0x2a): relocation truncated to fit: R_ARM_ABS16 against symbol `memu_armStmRdTable' defined in .dtcm section in ArmLdmStmRd.o
(.dtcm+0x30): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status
make[3]: *** [/home/godreborn/GBARunner3/code/test/arm9/Makefile:146: /home/godreborn/GBARunner3/code/test/arm9/test.elf] Error 1
make[2]: *** [Makefile:130: build] Error 2
make[2]: Leaving directory '/home/godreborn/GBARunner3/code/test/arm9'
make[1]: *** [Makefile:35: checkarm9] Error 2
make[1]: Leaving directory '/home/godreborn/GBARunner3/code/test'
make: *** [Makefile:30: checktest] Error 2

**Comment by godreborn** [comment]
I got it to compile through some effort, but on twilight menu I get a red, then green screen.  it doesn't freeze.  it just does nothing.  here's the size of the nds: 
![image](https://github.com/Gericom/GBARunner3/assets/13548481/473ee7ef-3bc9-44d9-8dec-355edb59b04d)

**Comment by Gericom** [comment]
Did you put the bios in /_gba/bios.bin? (And a rom in /rom.gba if you are not using argv)

May I also ask how you fixed your compilation issue. Some other people had this issue as well.

**Comment by godreborn** [comment]
the missing bios was the problem:

![20230926_082429](https://github.com/Gericom/GBARunner3/assets/13548481/bfa7e8f6-d843-4c49-8c06-357ac2f156d5)

how I got it to build was by not using the main make file.  I think I used the one in arm9, then bootstrap.

**Comment by godreborn** [comment]
btw, what is the difference between bootstrap.nds and test.nds?  I'm using bootstrap.nds, renamed to GBARunner3.nds for twilight menu in the above picture.  the game has no sound, but I assume that's normal for now.  the size seems awfully small for an emulator.

**Comment by Gericom** [comment]
test.nds contains unit tests. But they are only useful on dev hardware.

**Comment by godreborn** [comment]
[bootstrap.zip](https://github.com/Gericom/GBARunner3/files/12738731/bootstrap.zip)

here's my build for anyone who needs it.  rename the file for twilightmenu, plus you need to add that one line in settings.  it won't be there, so you need to include it along with 1 (enable).
