### ISSUE TITLE
Will this have an singular releases for the r4 

### ISSUE THREAD

**Issue by Rnzei** [Gericom/GBARunner3#35]

**Comment by RocketRobz** [comment]
@Rnzei As GBARunner3 will not have it's own menu, it'll be run by launching a GBA game via TWiLight Menu++.
If you we're to run the `.nds` file by itself though, you'd first need to put `rom.gba` on the SD root.

**Comment by Rnzei** [comment]
S it will have an nds file itself will it have its directory in the future
too like in gbarumner2

**Comment by RocketRobz** [comment]
> S it will have an nds file itself will it have its directory in the future too like in gbarumner2

Yes, it'll use the `_gba` folder like in GBARunner2.
