### ISSUE TITLE
Top Gun Combat Zones doesn't get past Main Menu due to checking savetypes when not using saves

### ISSUE THREAD

**Issue by zenseii** [Gericom/GBARunner3#38]
The game does not react to A-button inputs on main menu prohibiting you from getting past the main menu.
The game actually uses password saves.
Check comment from here: https://datomatic.no-intro.org/index.php?page=show_record&s=23&n=1903

```
"Top Gun - Combat Zones" is listed as having save-type "Flash512_v131" but this is not the case.
In fact, the game follows the heuristics for *every* save-type as an anti-piracy measure.
If it finds any non-volatile storage, it disables all the main-menu options.
```

According to datomatic it uses Flash512_v131

**Comment by Dartz150** [comment]
Apparently this is an AP measure, it works correctly by patching the check using this patch:

`00088817: 35 -> 34`
`0011CA14: 46 4C 41 53 48 35 31 32 5F 56 31 33 31 -> 00 00 00 00 00 00 00 00 00 00 00 00 00`
`0011CA5D: 4C 41 53 48 31 4D 5F 56 31 30 32 -> 00 00 00 00 00 00 00 00 00 00 00`
`0011CC94: 53 52 41 4D 5F 56 31 31 33 -> 00 00 00 00 00 00 00 00 00`

**Comment by Dartz150** [comment]
An optimized patch that also works, since it only needs the save type strings to be undetected by GBARunner3:

`00088817: 35 -> 34`
`0011CA14: 46 -> 00`
`0011CA5D: 4C -> 00`
`0011CC94: 53 -> 00`
