### ISSUE TITLE
Magical Vacation crashes in cave

### ISSUE THREAD

**Issue by zenseii** [Gericom/GBARunner3#39]
The game hangs at seemingly varying points inside the cave straight to the right in the below save. It seems to be easier to trigger if pressing the pause button at any point in the cave before or after fighting the monster in the closed chest further inside. Sometimes crashes when entering the monster batlle.

Save from right before cave for GBARunner3:
[Magical Vacation (Japan).zip](https://github.com/Gericom/GBARunner3/files/12861561/Magical.Vacation.Japan.zip)

no$gba savestate:
[magicalVacationBeforeCaveOfCrash.zip](https://github.com/Gericom/GBARunner3/files/12861547/magicalVacationBeforeCaveOfCrash.zip)

Original opening post about now fixed issue about note hanging in pause menu:
<details>

When pausing the game a single note will keep playing while the rest of the music plays normally. Stops playing when you leave the pause menu. What note keeps playing depends on what is currently playing in the game music.

See comment further below about crashing.

Save state from ingame in no$gba. Press start to enter pause menu.
[magicalVacationRetainedNote.zip](https://github.com/Gericom/GBARunner3/files/12851150/magicalVacationRetainedNote.zip)

Savegame from GBARunner3
[Magical Vacation (Japan).zip](https://github.com/Gericom/GBARunner3/files/12861561/Magical.Vacation.Japan.zip)

</details>

**Comment by Dartz150** [comment]
[Console tested]
DS Lite

[Device used]
Ace3DS+ early clone with the 2014 label

[Game Info]
Magical Vacation JAP - TID: AMVJ

With the testing environment mentioned above, this issue doesn't happen, while in DSi mode it can be reproduced.

**Comment by zenseii** [comment]
**EDIT: Moved to opening statement.**

Not sure if we want a separate issue for this game.

The game also hangs at seemingly varying points inside the cave straight to the right in this save. It seems to be easier to trigger if pressing the pause button at any point in the cave before or after fighting the monster in the closed chest further inside. Sometimes crashes when entering the monster batlle.

Save from right before cave for GBARunner3:
[Magical Vacation (Japan).zip](https://github.com/Gericom/GBARunner3/files/12861561/Magical.Vacation.Japan.zip)


no$gba savestate:
[magicalVacationBeforeCaveOfCrash.zip](https://github.com/Gericom/GBARunner3/files/12861547/magicalVacationBeforeCaveOfCrash.zip)

**Comment by Dartz150** [comment]
This sound issue no longer happens in both DS and DSi, tested with https://github.com/Gericom/GBARunner3/commit/cb168c8537ce3c0c39d77265e8eabaff8e39ce33, however, the freezing issue is still happening, so the issue should its name changed.

**Comment by Dartz150** [comment]
Tested on [36dcaa1](https://github.com/Gericom/GBARunner3/commit/36dcaa19991bbac585d678b4fd167f80017b6bcc), the issue no longer happens, however, the game crashes with manual JIT patches on DSi as mentioned in #110

**Comment by Gericom** [comment]
Can this issue be closed? Since a new one was created
