### ISSUE TITLE
where to download GBARUNNER3(bootstrap.nds)!thanks!

### ISSUE THREAD

**Issue by lxg1202** [Gericom/GBARunner3#41]
I want to play GBARUNNER3 on twilghtmenu(NDSI),but I donot find GBARUNNER3 download link!
please tell me !THANKS!

**Comment by therealteamplayer** [comment]
From what I can tell it is nowhere near finished yet, so if you want it right now you will have to build it yourself.

**Comment by Gericom** [comment]
There is no stable release yet. When the time comes there will be releases here on Github. In the meantime you can compile by yourself. In the DSi Mode Hacking discord server builds are also shared sometimes.
