### ISSUE TITLE
[Flashcard] Megaman & Bass freezes on a black screen after the BIOS logo

### ISSUE THREAD

**Issue by Dartz150** [Gericom/GBARunner3#42]
[Console tested]
DS Lite

[Device used]
Ace3DS+ early clone with the 2014 label

[Game Info]
Megaman & Bass USA - TID: A6ME

[Issue Description]
On DSi mode this game works fine using the same flashcard, tested with the latest feature/sound branch commit.

**Comment by Dartz150** [comment]
Re-formatted my SD card and the issue is gone, the game loads fine now, this can be closed. 

This could be related to #37

**Comment by zenseii** [comment]
> Re-formatted my SD card and the issue is gone, the game loads fine now, this can be closed.
> 
> This could be related to #37

Did you make an image of your SD card, or did you make the same mistake as me 😅
