### ISSUE TITLE
[Game] The Mummy doesn't work correctly in DSi mode, works in DS mode

### ISSUE THREAD

**Issue by Dartz150** [Gericom/GBARunner3#55]
[Game]
Mummy, The | AUME | USA

[Device Info]
Commit tested: 79dc7f0
Branch: feature/jit-detach
Console: DSi/DS
Device: SD Card/Ace3DS+

[Issue]
The games works in DS mode with not noticeable issues, while in DSi mode, the sound is screeching, stutters in performance, and sometimes the game music can be heard behind. DSi Power button needs to be held in for a while to power off.

**Comment by RocketRobz** [comment]
Setting main memory priority to arm7 (which I have not tried) seems to have fixed the issue.

**Comment by Dartz150** [comment]
**Game Info**
Lara Croft Tomb Raider - The Prophecy | AL9E | USA

This game has the same issue, and setting the main memory priority to ARM7 also fixes the issue.

**Comment by Dartz150** [comment]
Ths has been fixed with ewram data cache implementation in 90a6c7f, closed
