### ISSUE TITLE
[Game] Kong - The Animated Series boots with screeching sounds and a white screen

### ISSUE THREAD

**Issue by Dartz150** [Gericom/GBARunner3#67]
**Game**
Kong - The Animated Series | AKQE | USA

**Device Info**
Commit tested: https://github.com/Gericom/GBARunner3/commit/cb33f3507474bdf50bdda6bbddd82625a882329f
Branch: develop
Console: DSi
Device: SD

**Issue**
This game also has issues in NO$GBA, where only a green screen is shown in the whole game. Included DMA I/O map as reference.

![image](https://github.com/Gericom/GBARunner3/assets/42103728/5dc70c8a-5dfc-463d-b97e-defba17f688a)

**Comment by Gericom** [comment]
I believe this game worked on gbarunner2, but only dsi/3ds. So maybe there is some hicode?

**Comment by Gericom** [comment]
It is caused by some large-offset pc relative memory accesses when the game relocates code to iwram. Note that this is unrelated to the problem no$gba had.

![image](https://github.com/Gericom/GBARunner3/assets/5251038/f0d6b40a-007c-43ad-84b2-b2613819dd0e)
