### ISSUE TITLE
[Game] bit Generations - Dialhex and bit Generations - Dotstream freeze the console

### ISSUE THREAD

**Issue by Dartz150** [Gericom/GBARunner3#79]
### Game Info
**Game Title:** bit Generations - Dialhex, bit Generations - Dotstream
**TID:** BVBJ, BVCJ
**REG:** JAP
### GBARunner3 info
**Commit:** bc88606
**Build Date:** 26 Oct 2023
**Branch:** hicode
**Manual JIT:** ✔
### Hardware
**Console:** DSi
**Device:** SD
**Flashcard Model:** 

 ### **Compatibility:** Unbootable

**Notes:** Both freeze the console right before or at the H&S on a white screen, a power off needs to be forced. Manual JIT patches gives the same results.

**Comment by Gericom** [comment]
Did you test at DS speed?

**Comment by Dartz150** [comment]
> Did you test at DS speed?

Yes, the issue still happens with both.
