### ISSUE TITLE
[Game] 007 - NightFire - Cursor jumps up and down randomly

### ISSUE THREAD

**Issue by Dartz150** [Gericom/GBARunner3#80]
### Game Info
**Game Title:** 007 - NightFire
**TID:** A7OE
**REG:** USA
### GBARunner3 info
**Commit:** ba8cd01
**Build Date:** 28 Oct 2023
**Branch:** implement-bitmap-modes
**Manual JIT:** ✔
### Hardware
**Console:** DSi
**Device:** Flashcard
**Flashcard Model:** Ace3DS+

 ### **Compatibility:** Minor Issues

**Notes:** Loud screeching sounds in DSi mode as described in #73. Also, menu selection arrow jumps randomly in the screen, making it difficult to make any selection, this happens in both DS and DSi modes, and with manual JIT patches enabled.

(SS for reference)
![image](https://github.com/Gericom/GBARunner3/assets/42103728/2181b679-d8e5-426f-b8da-2d44df61b790)

**Comment by Dartz150** [comment]
This issue no longer occurs starting from commit c48ac4d, closed.

**Comment by Gericom** [comment]
Was it exactly that commit 🤔
