### ISSUE TITLE
[Game] Minna no Soft Series - Minna no Shougi has no sound by default

### ISSUE THREAD

**Issue by Dartz150** [Gericom/GBARunner3#83]
### Game Info
**Game Title:** Minna no Soft Series - Minna no Shougi
**TID:** BSGJ
**REG:** JAP
### GBARunner3 info
**Commit:** ba8cd01
**Build Date:** 28 Oct 2023
**Branch:** implement-bitmap-modes
**Manual JIT:** 
### Hardware
**Console:** DSi
**Device:** SD
**Flashcard Model:** 

 ### **Compatibility:** Sound Issues

**Notes:** Sound is turned off by default. To turn it on, select the last option in the first menu, then select the last option again and press left or right. Could be related to #70

**Comment by NagaseKouichi** [comment]
Minna no Soft Series - Zooo has the same problem. I didn't know I can turn on the sound in option untill I saw this post. Thank you.
