### ISSUE TITLE
[Game] Monster Truck Madness - White screens if there's an existing savefile

### ISSUE THREAD

**Issue by Dartz150** [Gericom/GBARunner3#88]
### Game Info
**Game Title:** Monster Truck Madness
**TID:** BMTE
**REG:** USA
### GBARunner3 info
**Commit:** ba8cd01
**Build Date:** 28 Oct 2023
**Branch:** bitmap-modes
**Manual JIT:** ✔
### Hardware
**Console:** DSi/DS Lite
**Device:** SD/Flashcard
**Flashcard Model:** Ace3DS+

 ### **Compatibility:** Unbootable

**Notes:** The game works fine at the first boot with a fresh save file, but it white screens if you try to boot it again with an existing save file. Manual JIT patches fixes the issue, I'll PR this later as I'm gathering more JIT patch fixes for other games.

Here's the config file for the fix in the meantime:
[BMTE00.json](https://github.com/Gericom/GBARunner3/files/13199018/BMTE00.json)

**Comment by zenseii** [comment]
This sounds very similar to the behavior of Big Mutha Truckers.

**Comment by Dartz150** [comment]
Added JIT patches in db8811b fixes the game, closed.
