### ISSUE TITLE
[Game] Big Mutha Truckers gets stuck on the title screen and has no sound

### ISSUE THREAD

**Issue by Dartz150** [Gericom/GBARunner3#89]
### Game Info
**Game Title:** Big Mutha Truckers
**TID:** B63E
**REG:** USA
### GBARunner3 info
**Commit:** c0aca97
**Build Date:** 29 Oct 2023
**Branch:** develop
**Manual JIT:** ✔
### Hardware
**Console:** DSi/DS
**Device:** SD/Flashcard
**Flashcard Model:** Ace3DS+

 ### **Compatibility:** Unplayable

**Notes:** It gives a black screen after the bios. Pressing buttons gets to the title screen which only says "press start", with no background even on bitmap branch. Main menu is locked on a message "save game corrupted". There's also no sound. Removed the save and didn't get the save error message, but the main menu did not react to any inputs. Hicode branch behaves the same, JIT patches and disabled icache didn't help either. DS mode also gives the same result.

**Comment by Gericom** [comment]
The problem is code in vram.
