### ISSUE TITLE
[Game] Monsters, Inc. - Game crashes after language selection/company logos

### ISSUE THREAD

**Issue by Dartz150** [Gericom/GBARunner3#90]
### Game Info
**Game Title:** Monsters, Inc.
**TID:** AMXE, AMXP, AMXX, AMXJ
**REG:** USA, EUR, JAP
### GBARunner3 info
**Commit:** ba8cd01
**Build Date:** 28 Oct 2023
**Branch:** bitmap-modes
**Manual JIT:** ✔
### Hardware
**Console:** DSi
**Device:** SD
**Flashcard Model:** 

 ### **Compatibility:** Unplayable

**Notes:** The game freezes after the language selection in the EUR versions, and after the company logos in the US/JP versions. JIT patches didn't help, disabling cache either. The same happens in DS mode.

**Comment by Gericom** [comment]
Fixed
